# Generated by Django 4.2.3 on 2023-08-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_fname_membership_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='where_did_you_here_about_us',
            new_name='where_did_you_hear_about_us',
        ),
    ]
